name: build

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always
  KAFKA_BROKER_ENDPOINT: ${{ secrets.KAFKA_BROKER_ENDPOINT }}
  KAFKA_CLUSTER_API_KEY: ${{ secrets.KAFKA_CLUSTER_API_KEY }}
  KAFKA_CLUSTER_API_SECRET: ${{ secrets.KAFKA_CLUSTER_API_SECRET }}

  X86_64_UNKNOWN_LINUX_MUSL_OPENSSL_DIR: /usr/local/musl/
  X86_64_UNKNOWN_LINUX_MUSL_OPENSSL_STATIC: 1
  PG_CONFIG_X86_64_UNKNOWN_LINUX_GNU: /usr/bin/pg_config
  PKG_CONFIG_ALLOW_CROSS: true
  PKG_CONFIG_ALL_STATIC: true
  LIBZ_SYS_STATIC: 1
  TARGET: musl
  TARGET_CC: x86_64-unknown-linux-musl-cc
  TARGET_CXX: x86_64-unknown-linux-musl-c++
  CMAKE_SYSTEM_NAME: Linux

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: sudo apt-get install -y musl-tools pkgconf libssl-dev
      - run: rustup target add x86_64-unknown-linux-musl
      - run: rustup target list --installed
      - run: openssl version
      - run: cargo version
      - run: sudo ln -s /usr/bin/g++ /usr/bin/musl-g++
      - run: cargo test --verbose --target x86_64-unknown-linux-musl
      - run: cargo build --verbose --target x86_64-unknown-linux-musl
      - run: cargo test --verbose
      - run: cargo build --verbose
