name: build

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always
  KAFKA_BROKER_ENDPOINT: ${{ secrets.KAFKA_BROKER_ENDPOINT }}
  KAFKA_CLUSTER_API_KEY: ${{ secrets.KAFKA_CLUSTER_API_KEY }}
  KAFKA_CLUSTER_API_SECRET: ${{ secrets.KAFKA_CLUSTER_API_SECRET }}

  PKG_CONFIG_ALLOW_CROSS: 1

jobs:
  build:
    name: Build ${{ matrix.target }}

    runs-on: ubuntu-latest

    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-gnu
          - x86_64-unknown-linux-musl

    steps:
      - uses: actions/checkout@v2
      - run: sudo apt-get install -y build-essential musl-dev musl-tools libssl-dev linux-musl-dev linux-libc-dev zlib1g-dev pkg-config
      - run: rustup target add ${{ matrix.target }}
      - run: openssl version
      - run: cargo version
      - run: sudo ln -s /usr/bin/g++ /usr/bin/musl-g++
        if: matrix.target == 'x86_64-unknown-linux-musl'
      - run: cargo test --verbose --target ${{ matrix.target }}
      - run: cargo build --verbose --target ${{ matrix.target }}
