name: build

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always
  KAFKA_BROKER_ENDPOINT: ${{ secrets.KAFKA_BROKER_ENDPOINT }}
  KAFKA_CLUSTER_API_KEY: ${{ secrets.KAFKA_CLUSTER_API_KEY }}
  KAFKA_CLUSTER_API_SECRET: ${{ secrets.KAFKA_CLUSTER_API_SECRET }}
  X86_64_UNKNOWN_LINUX_MUSL_OPENSSL_DIR: /usr/local/musl/
  X86_64_UNKNOWN_LINUX_MUSL_OPENSSL_STATIC: 1

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: sudo apt-get install -y musl-tools pkgconf libssl-dev
      - run: rustup target add x86_64-unknown-linux-musl
      - run: openssl version
      - run: cargo version
      - run: cargo test --verbose
      - run: sudo ln -s /usr/bin/g++ /usr/bin/musl-g++
      - run: LIB_LDFLAGS=-L/usr/lib/x86_64-linux-gnu CFLAGS=-I/usr/local/musl/include CC=musl-gcc cargo test --verbose --target x86_64-unknown-linux-musl
      - run: cargo build --verbose
      - run: cargo build --verbose --target x86_64-unknown-linux-musl
