name: build

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always
  KAFKA_BROKER_ENDPOINT: ${{ secrets.KAFKA_BROKER_ENDPOINT }}
  KAFKA_CLUSTER_API_KEY: ${{ secrets.KAFKA_CLUSTER_API_KEY }}
  KAFKA_CLUSTER_API_SECRET: ${{ secrets.KAFKA_CLUSTER_API_SECRET }}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: sudo apt-get install -y libssl-dev
      - run: cargo version
      - run: cargo build --verbose
      - run: openssl version
      - run: cargo test --verbose
